name: UsefulBuildersWand
main: net.teamfruit.ubw.UBWPlugin
version: 1.0.0
author: Kamesuta
commands:
  wand:
    description: UsefulBuilder'sWand commands
    usage: /wand <undo|redo|size|effect_radius|effect_color> [args...]
    permission: wand.grant
permissions:
  wand.use:
    description: You can use Builder's Wand
    default: true
  wand.grant:
    description: You can enable other's wand.
    default: op
